spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3310/graphql
    username: default_user
    password: password123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true